version: '2'
services:
  duplicate:
    build: duplicate
    depends_on:
      - db
    volumes:
      - ./wp-archive:/wp-archive
      - ./wp-data:/var/www/html
    environment:
      WORDPRESS_URL: http://localhost
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: tapflo
    networks:
      - wordpress-network
    ports:
      - 80:80 # change ip if required
  
  db:
    image: mysql:8 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    #command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306 # change ip if required
    volumes:
      - ./mysql-data:/var/lib/mysql
      #- ./wp-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: tapflo
    networks:
      - wordpress-network
networks:
  wordpress-network:
      driver: bridge

